# Generated by Django 2.0.3 on 2018-06-19 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('logbuch', '0001_initial'),
        ('main', '0002_auto_20180613_0833'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bild',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bild', models.ImageField(blank=True, null=True, upload_to='')),
                ('bewertung', models.FloatField(blank=True, null=True)),
                ('titel', models.CharField(blank=True, max_length=255, null=True)),
                ('kommentar', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('tagebucheintrag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='logbuch.Logbucheintrag')),
                ('tour', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Tour')),
            ],
        ),
    ]
