# Generated by Django 2.0.3 on 2018-06-15 15:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telebot', '0002_auto_20180613_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2018, 6, 15, 15, 28, 35, 440183)),
            preserve_default=False,
        ),
    ]
