# Generated by Django 2.0.3 on 2018-06-12 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('short', models.CharField(max_length=10)),
                ('lon', models.FloatField(default=0, null=True)),
                ('lat', models.FloatField(default=0, null=True)),
                ('url', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('alias', models.CharField(max_length=250)),
                ('date_start', models.DateField(auto_now=True, verbose_name='Tour Started')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, null=True)),
                ('chatid', models.IntegerField()),
                ('date_active', models.DateTimeField(auto_now=True, verbose_name='Last Activity')),
                ('date_signed', models.DateTimeField(auto_now=True, verbose_name='User Registred')),
            ],
        ),
    ]
