# Generated by Django 2.0.3 on 2018-06-13 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='alias',
            field=models.CharField(max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='tour',
            name='date_start',
            field=models.DateField(null=True, verbose_name='Tour Started'),
        ),
    ]
