# Generated by Django 2.0.3 on 2018-06-12 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logbucheintrag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('erstellt', models.DateTimeField(auto_now=True, verbose_name='Erstellt am')),
                ('bearbeitet', models.DateTimeField(auto_now=True, verbose_name='Bearbeitet am')),
                ('datum', models.DateTimeField(blank=True, null=True, verbose_name='Datum')),
                ('tag', models.IntegerField(blank=True, null=True, verbose_name='Tag Nummer')),
                ('text', models.TextField(blank=True, null=True)),
                ('strecke', models.FloatField(blank=True, null=True)),
                ('uptime', models.FloatField(blank=True, null=True)),
                ('hoehe', models.FloatField(blank=True, null=True)),
                ('gps_lon', models.FloatField(blank=True, null=True)),
                ('gps_lat', models.FloatField(blank=True, null=True)),
                ('tour', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Tour')),
            ],
        ),
    ]
